service: apollo-server

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

plugins:
  - serverless-offline

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
